name: learn-github-action
on: [push]
jobs:
  checkout-bats-version1:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with: 
       node-version: '14'
    - run: npm install -g bats
    - run: bats -v
  checkout-bats-version2:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with: 
       node-version: '14'
    - run: npm install -g bats
    - run: bats -v